# Generated by Django 4.0.5 on 2022-10-01 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('comp_name', models.CharField(max_length=100)),
                ('ph_no', models.CharField(max_length=12)),
                ('webs_name', models.URLField()),
                ('serv_insterest', models.OneToOneField(choices=[], on_delete=django.db.models.deletion.CASCADE, to='base.servicemodel')),
            ],
        ),
    ]
