# Generated by Django 4.0.5 on 2022-10-01 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_customersmodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersmodels',
            name='serv_insterest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.servicemodel'),
        ),
    ]
