# Generated by Django 4.0.5 on 2022-10-01 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_customersmodels_serv_insterest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersmodels',
            old_name='serv_insterest',
            new_name='service_insterested',
        ),
        migrations.CreateModel(
            name='PackageModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack1', models.CharField(max_length=200)),
                ('price1', models.CharField(max_length=200)),
                ('pack2', models.CharField(max_length=200)),
                ('price2', models.CharField(max_length=200)),
                ('pack3', models.CharField(max_length=200)),
                ('price3', models.CharField(max_length=200)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.servicemodel')),
            ],
        ),
    ]
