# Generated by Django 4.0.5 on 2022-10-01 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_serv_insterest_customersmodels_service_insterested_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomersModels',
            new_name='CustomersModel',
        ),
        migrations.RenameModel(
            old_name='PackageModels',
            new_name='PackageModel',
        ),
    ]
