# Generated by Django 4.0.5 on 2022-10-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_customersmodels_customersmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersmodel',
            old_name='ph_no',
            new_name='phone_no',
        ),
        migrations.RemoveField(
            model_name='customersmodel',
            name='comp_name',
        ),
        migrations.RemoveField(
            model_name='customersmodel',
            name='webs_name',
        ),
        migrations.AddField(
            model_name='customersmodel',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customersmodel',
            name='tell_us_about_your_business',
            field=models.TextField(default='ajfsds', max_length=2000),
        ),
        migrations.AddField(
            model_name='customersmodel',
            name='website_name',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customersmodel',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
