# Generated by Django 4.0.5 on 2022-10-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_customersmodel_tell_us_about_your_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersmodel',
            old_name='website_name',
            new_name='website_URL',
        ),
    ]
