# Generated by Django 4.0.5 on 2022-10-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_customersmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
